### ISSUE TITLE
-s flag results in failure with ImageMagick 7

### ISSUE THREAD

**Issue by Granshmeyr** [quantum5/win2xcur#11]
~ $ win2xcur Bibata-Modern-Ice-Windows/*.{ani,cur} -s -o output/
    Traceback (most recent call last):
      File "/data/data/com.termux/files/usr/bin/win2xcur", line 8, in <module>
        sys.exit(main())
      File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/win2xcur/main/win2xcur.py", line 58, in main
        pool.map(process, args.files)
      File "/data/data/com.termux/files/usr/lib/python3.10/multiprocessing/pool.py", line 364, in map
        return self._map_async(func, iterable, mapstar, chunksize).get()
      File "/data/data/com.termux/files/usr/lib/python3.10/multiprocessing/pool.py", line 771, in get
        raise self._value
      File "/data/data/com.termux/files/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
        result = (True, func(*args, **kwds))
      File "/data/data/com.termux/files/usr/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
        return list(map(*args))
      File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/win2xcur/main/win2xcur.py", line 50, in process
        shadow.apply_to_frames(cursor.frames, color=args.shadow_color, radius=args.shadow_radius,
      File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/win2xcur/shadow.py", line 39, in apply_to_frames
        cursor.image = apply_to_image(cursor.image, color=color, radius=radius,
      File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/win2xcur/shadow.py", line 23, in apply_to_image
        shadow.composite(opacity, operator='copy_opacity')
      File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/wand/image.py", line 1098, in wrapped
        result = function(self, *args, **kwargs)
      File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/wand/image.py", line 3906, in composite
        op = COMPOSITE_OPERATORS.index(operator)
    ValueError: tuple.index(x): x not in tuple
I experienced this error in both Arch and Termux. I read [this](https://stackoverflow.com/questions/30377602/python-wand-composite-image-with-transparency#comment112574418_30382210) which prompted me to install ImageMagick 6 rather than 7, and afterwards the script functioned correctly.

Not a big deal, but I don't see it documented anywhere that the script explicitly requires ImageMagick version 6. You should, in my opinion, at least add a warning to the readme for average joes such as myself.

**Comment by quantum5** [comment]
This appears to be a simple rename. I pushed ffb9c5e24a166e567041fbeb9283b641f29efef1 which contains a fix. Please let me know if it works on ImageMagick 7 since I don't have it on Debian and I'll make a new release.

**Comment by Granshmeyr** [comment]
I tested using `win2xcur source/*.{ani,cur} -s -o output/` on three distributions: Debian, Termux, and Arch.
- Debian = ImageMagick 6.9.11-60
- Termux = ImageMagick 7.1.0-16
- Arch = ImageMagick 7.1.0-29

The script worked on all distributions; however, the output itself was incorrect on Termux and Arch. Here is an image showing the outputs in the previously listed order:

![image](https://user-images.githubusercontent.com/80663569/162597125-c9372768-2b4c-484e-83e3-d7aa8f442442.png)

**Comment by quantum5** [comment]
This should be fixed in 78637759218de6dd24f5cf13ed95c62afbae24ba. Sorry it took so long.

**Comment by Weathercold** [comment]
Hello. It's been a year since the last release, can you create a new release on PyPI to include this fix? Thanks in advance.

**Comment by quantum5** [comment]
Thanks for the reminder, released.
