### ISSUE TITLE
Possible Bug: Can not convert entirety of Thane Techline Curors

### ISSUE THREAD

**Issue by Saijin-Naib** [quantum5/win2xcur#8]
I am trying to use win2xcur under Python 3.9 on Alpine Linux Edge and it fails to convert this entire set, which I know to be valid (ish) since I've been using it on Windows since about 2001.

https://download.cnet.com/Techline-Cursor-Pack/3000-2317_4-10062532.html

Error Dump:  
```
/win2xcur -s ~/Downloads/thane-techline/*.* -o ~/
Error occurred while processing /home/alpine/Downloads/thane-techline/arrow.cur:
Traceback (most recent call last):
  File "/home/alpine/.local/lib/python3.9/site-packages/win2xcur/main/win2xcur.py", line 43, in process
    cursor = open_blob(blob)
  File "/home/alpine/.local/lib/python3.9/site-packages/win2xcur/parser/__init__.py", line 16, in open_blob
    return parser(blob)
  File "/home/alpine/.local/lib/python3.9/site-packages/win2xcur/parser/cur.py", line 22, in __init__
    self._image = Image(blob=blob, format='cur')
  File "/home/alpine/.local/lib/python3.9/site-packages/wand/image.py", line 9142, in __init__
    self.read(blob=blob)
  File "/home/alpine/.local/lib/python3.9/site-packages/wand/image.py", line 9815, in read
    self.raise_exception()
  File "/home/alpine/.local/lib/python3.9/site-packages/wand/resource.py", line 222, in raise_exception
    raise e
wand.exceptions.MissingDelegateError: NoDecodeDelegateForThisImageFormat `CUR' @ error/blob.c/BlobToImage/458
Error occurred while processing /home/alpine/Downloads/thane-techline/alt.cur:
Traceback (most recent call last):
  File "/home/alpine/.local/lib/python3.9/site-packages/win2xcur/main/win2xcur.py", line 43, in process
    cursor = open_blob(blob)
  File "/home/alpine/.local/lib/python3.9/site-packages/win2xcur/parser/__init__.py", line 16, in open_blob
    return parser(blob)
  File "/home/alpine/.local/lib/python3.9/site-packages/win2xcur/parser/cur.py", line 22, in __init__
    self._image = Image(blob=blob, format='cur')
  File "/home/alpine/.local/lib/python3.9/site-packages/wand/image.py", line 9142, in __init__
    self.read(blob=blob)
  File "/home/alpine/.local/lib/python3.9/site-packages/wand/image.py", line 9815, in read
    self.raise_exception()
  File "/home/alpine/.local/lib/python3.9/site-packages/wand/resource.py", line 222, in raise_exception
    raise e
wand.exceptions.MissingDelegateError: NoDecodeDelegateForThisImageFormat `CUR' @ error/blob.c/BlobToImage/458
Error occurred while processing /home/alpine/Downloads/thane-techline/busy.ani:
Traceback (most recent call last):
  File "/home/alpine/.local/lib/python3.9/site-packages/win2xcur/main/win2xcur.py", line 43, in process
    cursor = open_blob(blob)
  File "/home/alpine/.local/lib/python3.9/site-packages/win2xcur/parser/__init__.py", line 16, in open_blob
    return parser(blob)
  File "/home/alpine/.local/lib/python3.9/site-packages/win2xcur/parser/ani.py", line 41, in __init__
    self.frames = self._parse(self.RIFF_HEADER.size)
  File "/home/alpine/.local/lib/python3.9/site-packages/win2xcur/parser/ani.py", line 91, in _parse
    frames.append(CURParser(self.blob[offset:offset + size]).frames[0])
  File "/home/alpine/.local/lib/python3.9/site-packages/win2xcur/parser/cur.py", line 22, in __init__
    self._image = Image(blob=blob, format='cur')
  File "/home/alpine/.local/lib/python3.9/site-packages/wand/image.py", line 9142, in __init__
    self.read(blob=blob)
  File "/home/alpine/.local/lib/python3.9/site-packages/wand/image.py", line 9815, in read
    self.raise_exception()
  File "/home/alpine/.local/lib/python3.9/site-packages/wand/resource.py", line 222, in raise_exception
    raise e
wand.exceptions.MissingDelegateError: NoDecodeDelegateForThisImageFormat `CUR' @ error/blob.c/BlobToImage/458
Error occurred while processing /home/alpine/Downloads/thane-techline/forbbiden.cur:
Traceback (most recent call last):
  File "/home/alpine/.local/lib/python3.9/site-packages/win2xcur/main/win2xcur.py", line 43, in process
    cursor = open_blob(blob)
  File "/home/alpine/.local/lib/python3.9/site-packages/win2xcur/parser/__init__.py", line 16, in open_blob
    return parser(blob)
  File "/home/alpine/.local/lib/python3.9/site-packages/win2xcur/parser/cur.py", line 22, in __init__
    self._image = Image(blob=blob, format='cur')
  File "/home/alpine/.local/lib/python3.9/site-packages/wand/image.py", line 9142, in __init__
    self.read(blob=blob)
  File "/home/alpine/.local/lib/python3.9/site-packages/wand/image.py", line 9815, in read
    self.raise_exception()
  File "/home/alpine/.local/lib/python3.9/site-packages/wand/resource.py", line 222, in raise_exception
    raise e
wand.exceptions.MissingDelegateError: NoDecodeDelegateForThisImageFormat `CUR' @ error/blob.c/BlobToImage/458
Error occurred while processing /home/alpine/Downloads/thane-techline/handwri.cur:
Traceback (most recent call last):
  File "/home/alpine/.local/lib/python3.9/site-packages/win2xcur/main/win2xcur.py", line 43, in process
    cursor = open_blob(blob)
  File "/home/alpine/.local/lib/python3.9/site-packages/win2xcur/parser/__init__.py", line 16, in open_blob
    return parser(blob)
  File "/home/alpine/.local/lib/python3.9/site-packages/win2xcur/parser/cur.py", line 22, in __init__
    self._image = Image(blob=blob, format='cur')
  File "/home/alpine/.local/lib/python3.9/site-packages/wand/image.py", line 9142, in __init__
    self.read(blob=blob)
  File "/home/alpine/.local/lib/python3.9/site-packages/wand/image.py", line 9815, in read
    self.raise_exception()
  File "/home/alpine/.local/lib/python3.9/site-packages/wand/resource.py", line 222, in raise_exception
    raise e
wand.exceptions.MissingDelegateError: NoDecodeDelegateForThisImageFormat `CUR' @ error/blob.c/BlobToImage/458
Error occurred while processing /home/alpine/Downloads/thane-techline/help.cur:
Traceback (most recent call last):
  File "/home/alpine/.local/lib/python3.9/site-packages/win2xcur/main/win2xcur.py", line 43, in process
    cursor = open_blob(blob)
  File "/home/alpine/.local/lib/python3.9/site-packages/win2xcur/parser/__init__.py", line 16, in open_blob
    return parser(blob)
  File "/home/alpine/.local/lib/python3.9/site-packages/win2xcur/parser/cur.py", line 22, in __init__
    self._image = Image(blob=blob, format='cur')
  File "/home/alpine/.local/lib/python3.9/site-packages/wand/image.py", line 9142, in __init__
    self.read(blob=blob)
  File "/home/alpine/.local/lib/python3.9/site-packages/wand/image.py", line 9815, in read
    self.raise_exception()
  File "/home/alpine/.local/lib/python3.9/site-packages/wand/resource.py", line 222, in raise_exception
    raise e
wand.exceptions.MissingDelegateError: NoDecodeDelegateForThisImageFormat `CUR' @ error/blob.c/BlobToImage/458
Error occurred while processing /home/alpine/Downloads/thane-techline/link.cur:
Traceback (most recent call last):
  File "/home/alpine/.local/lib/python3.9/site-packages/win2xcur/main/win2xcur.py", line 43, in process
    cursor = open_blob(blob)
  File "/home/alpine/.local/lib/python3.9/site-packages/win2xcur/parser/__init__.py", line 16, in open_blob
    return parser(blob)
  File "/home/alpine/.local/lib/python3.9/site-packages/win2xcur/parser/cur.py", line 22, in __init__
    self._image = Image(blob=blob, format='cur')
  File "/home/alpine/.local/lib/python3.9/site-packages/wand/image.py", line 9142, in __init__
    self.read(blob=blob)
  File "/home/alpine/.local/lib/python3.9/site-packages/wand/image.py", line 9815, in read
    self.raise_exception()
  File "/home/alpine/.local/lib/python3.9/site-packages/wand/resource.py", line 222, in raise_exception
    raise e
wand.exceptions.MissingDelegateError: NoDecodeDelegateForThisImageFormat `CUR' @ error/blob.c/BlobToImage/458
Error occurred while processing /home/alpine/Downloads/thane-techline/move.cur:
Traceback (most recent call last):
  File "/home/alpine/.local/lib/python3.9/site-packages/win2xcur/main/win2xcur.py", line 43, in process
    cursor = open_blob(blob)
  File "/home/alpine/.local/lib/python3.9/site-packages/win2xcur/parser/__init__.py", line 16, in open_blob
    return parser(blob)
  File "/home/alpine/.local/lib/python3.9/site-packages/win2xcur/parser/cur.py", line 22, in __init__
    self._image = Image(blob=blob, format='cur')
  File "/home/alpine/.local/lib/python3.9/site-packages/wand/image.py", line 9142, in __init__
    self.read(blob=blob)
  File "/home/alpine/.local/lib/python3.9/site-packages/wand/image.py", line 9815, in read
    self.raise_exception()
  File "/home/alpine/.local/lib/python3.9/site-packages/wand/resource.py", line 222, in raise_exception
    raise e
wand.exceptions.MissingDelegateError: NoDecodeDelegateForThisImageFormat `CUR' @ error/blob.c/BlobToImage/458
Error occurred while processing /home/alpine/Downloads/thane-techline/precision.cur:
Traceback (most recent call last):
  File "/home/alpine/.local/lib/python3.9/site-packages/win2xcur/main/win2xcur.py", line 43, in process
    cursor = open_blob(blob)
  File "/home/alpine/.local/lib/python3.9/site-packages/win2xcur/parser/__init__.py", line 16, in open_blob
    return parser(blob)
  File "/home/alpine/.local/lib/python3.9/site-packages/win2xcur/parser/cur.py", line 22, in __init__
    self._image = Image(blob=blob, format='cur')
  File "/home/alpine/.local/lib/python3.9/site-packages/wand/image.py", line 9142, in __init__
    self.read(blob=blob)
  File "/home/alpine/.local/lib/python3.9/site-packages/wand/image.py", line 9815, in read
    self.raise_exception()
  File "/home/alpine/.local/lib/python3.9/site-packages/wand/resource.py", line 222, in raise_exception
    raise e
wand.exceptions.MissingDelegateError: NoDecodeDelegateForThisImageFormat `CUR' @ error/blob.c/BlobToImage/458
Error occurred while processing /home/alpine/Downloads/thane-techline/res-diag1.ani:
Traceback (most recent call last):
  File "/home/alpine/.local/lib/python3.9/site-packages/win2xcur/main/win2xcur.py", line 43, in process
    cursor = open_blob(blob)
  File "/home/alpine/.local/lib/python3.9/site-packages/win2xcur/parser/__init__.py", line 16, in open_blob
    return parser(blob)
  File "/home/alpine/.local/lib/python3.9/site-packages/win2xcur/parser/ani.py", line 41, in __init__
    self.frames = self._parse(self.RIFF_HEADER.size)
  File "/home/alpine/.local/lib/python3.9/site-packages/win2xcur/parser/ani.py", line 91, in _parse
    frames.append(CURParser(self.blob[offset:offset + size]).frames[0])
  File "/home/alpine/.local/lib/python3.9/site-packages/win2xcur/parser/cur.py", line 22, in __init__
    self._image = Image(blob=blob, format='cur')
  File "/home/alpine/.local/lib/python3.9/site-packages/wand/image.py", line 9142, in __init__
    self.read(blob=blob)
  File "/home/alpine/.local/lib/python3.9/site-packages/wand/image.py", line 9815, in read
    self.raise_exception()
  File "/home/alpine/.local/lib/python3.9/site-packages/wand/resource.py", line 222, in raise_exception
    raise e
wand.exceptions.MissingDelegateError: NoDecodeDelegateForThisImageFormat `CUR' @ error/blob.c/BlobToImage/458
Error occurred while processing /home/alpine/Downloads/thane-techline/res-diag2.ani:
Traceback (most recent call last):
  File "/home/alpine/.local/lib/python3.9/site-packages/win2xcur/main/win2xcur.py", line 43, in process
    cursor = open_blob(blob)
  File "/home/alpine/.local/lib/python3.9/site-packages/win2xcur/parser/__init__.py", line 16, in open_blob
    return parser(blob)
  File "/home/alpine/.local/lib/python3.9/site-packages/win2xcur/parser/ani.py", line 41, in __init__
    self.frames = self._parse(self.RIFF_HEADER.size)
  File "/home/alpine/.local/lib/python3.9/site-packages/win2xcur/parser/ani.py", line 91, in _parse
    frames.append(CURParser(self.blob[offset:offset + size]).frames[0])
  File "/home/alpine/.local/lib/python3.9/site-packages/win2xcur/parser/cur.py", line 22, in __init__
    self._image = Image(blob=blob, format='cur')
  File "/home/alpine/.local/lib/python3.9/site-packages/wand/image.py", line 9142, in __init__
    self.read(blob=blob)
  File "/home/alpine/.local/lib/python3.9/site-packages/wand/image.py", line 9815, in read
    self.raise_exception()
  File "/home/alpine/.local/lib/python3.9/site-packages/wand/resource.py", line 222, in raise_exception
    raise e
wand.exceptions.MissingDelegateError: NoDecodeDelegateForThisImageFormat `CUR' @ error/blob.c/BlobToImage/458
Error occurred while processing /home/alpine/Downloads/thane-techline/res-horiz.ani:
Traceback (most recent call last):
  File "/home/alpine/.local/lib/python3.9/site-packages/win2xcur/main/win2xcur.py", line 43, in process
    cursor = open_blob(blob)
  File "/home/alpine/.local/lib/python3.9/site-packages/win2xcur/parser/__init__.py", line 16, in open_blob
    return parser(blob)
  File "/home/alpine/.local/lib/python3.9/site-packages/win2xcur/parser/ani.py", line 41, in __init__
    self.frames = self._parse(self.RIFF_HEADER.size)
  File "/home/alpine/.local/lib/python3.9/site-packages/win2xcur/parser/ani.py", line 91, in _parse
    frames.append(CURParser(self.blob[offset:offset + size]).frames[0])
  File "/home/alpine/.local/lib/python3.9/site-packages/win2xcur/parser/cur.py", line 22, in __init__
    self._image = Image(blob=blob, format='cur')
  File "/home/alpine/.local/lib/python3.9/site-packages/wand/image.py", line 9142, in __init__
    self.read(blob=blob)
  File "/home/alpine/.local/lib/python3.9/site-packages/wand/image.py", line 9815, in read
    self.raise_exception()
  File "/home/alpine/.local/lib/python3.9/site-packages/wand/resource.py", line 222, in raise_exception
    raise e
wand.exceptions.MissingDelegateError: NoDecodeDelegateForThisImageFormat `CUR' @ error/blob.c/BlobToImage/458
Error occurred while processing /home/alpine/Downloads/thane-techline/text.cur:
Traceback (most recent call last):
  File "/home/alpine/.local/lib/python3.9/site-packages/win2xcur/main/win2xcur.py", line 43, in process
    cursor = open_blob(blob)
  File "/home/alpine/.local/lib/python3.9/site-packages/win2xcur/parser/__init__.py", line 16, in open_blob
    return parser(blob)
  File "/home/alpine/.local/lib/python3.9/site-packages/win2xcur/parser/cur.py", line 22, in __init__
    self._image = Image(blob=blob, format='cur')
  File "/home/alpine/.local/lib/python3.9/site-packages/wand/image.py", line 9142, in __init__
    self.read(blob=blob)
  File "/home/alpine/.local/lib/python3.9/site-packages/wand/image.py", line 9815, in read
    self.raise_exception()
  File "/home/alpine/.local/lib/python3.9/site-packages/wand/resource.py", line 222, in raise_exception
    raise e
wand.exceptions.MissingDelegateError: NoDecodeDelegateForThisImageFormat `CUR' @ error/blob.c/BlobToImage/458
Error occurred while processing /home/alpine/Downloads/thane-techline/res-vert.ani:
Traceback (most recent call last):
  File "/home/alpine/.local/lib/python3.9/site-packages/win2xcur/main/win2xcur.py", line 43, in process
    cursor = open_blob(blob)
  File "/home/alpine/.local/lib/python3.9/site-packages/win2xcur/parser/__init__.py", line 16, in open_blob
    return parser(blob)
  File "/home/alpine/.local/lib/python3.9/site-packages/win2xcur/parser/ani.py", line 41, in __init__
    self.frames = self._parse(self.RIFF_HEADER.size)
  File "/home/alpine/.local/lib/python3.9/site-packages/win2xcur/parser/ani.py", line 91, in _parse
    frames.append(CURParser(self.blob[offset:offset + size]).frames[0])
  File "/home/alpine/.local/lib/python3.9/site-packages/win2xcur/parser/cur.py", line 22, in __init__
    self._image = Image(blob=blob, format='cur')
  File "/home/alpine/.local/lib/python3.9/site-packages/wand/image.py", line 9142, in __init__
    self.read(blob=blob)
  File "/home/alpine/.local/lib/python3.9/site-packages/wand/image.py", line 9815, in read
    self.raise_exception()
  File "/home/alpine/.local/lib/python3.9/site-packages/wand/resource.py", line 222, in raise_exception
    raise e
wand.exceptions.MissingDelegateError: NoDecodeDelegateForThisImageFormat `CUR' @ error/blob.c/BlobToImage/458
Error occurred while processing /home/alpine/Downloads/thane-techline/working.ani:
Traceback (most recent call last):
  File "/home/alpine/.local/lib/python3.9/site-packages/win2xcur/main/win2xcur.py", line 43, in process
    cursor = open_blob(blob)
  File "/home/alpine/.local/lib/python3.9/site-packages/win2xcur/parser/__init__.py", line 16, in open_blob
    return parser(blob)
  File "/home/alpine/.local/lib/python3.9/site-packages/win2xcur/parser/ani.py", line 41, in __init__
    self.frames = self._parse(self.RIFF_HEADER.size)
  File "/home/alpine/.local/lib/python3.9/site-packages/win2xcur/parser/ani.py", line 91, in _parse
    frames.append(CURParser(self.blob[offset:offset + size]).frames[0])
  File "/home/alpine/.local/lib/python3.9/site-packages/win2xcur/parser/cur.py", line 22, in __init__
    self._image = Image(blob=blob, format='cur')
  File "/home/alpine/.local/lib/python3.9/site-packages/wand/image.py", line 9142, in __init__
    self.read(blob=blob)
  File "/home/alpine/.local/lib/python3.9/site-packages/wand/image.py", line 9815, in read
    self.raise_exception()
  File "/home/alpine/.local/lib/python3.9/site-packages/wand/resource.py", line 222, in raise_exception
    raise e
wand.exceptions.MissingDelegateError: NoDecodeDelegateForThisImageFormat `CUR' @ error/blob.c/BlobToImage/458
```

**Comment by quantum5** [comment]
This looks like your inagemagick installation was built without support for the CUR file format. If you can't fix this, try it on a different machine with a different distro.

**Comment by Saijin-Naib** [comment]
Thanks. I added a different install of imagemagick, and got further, but still stumped. Do you know what this means?
```
./win2xcur -s ~/Downloads/thane-techline/alt.cur -o 
~/
Traceback (most recent call last):
  File "/home/alpine/.local/bin/./win2xcur", line 8, in <module>
    sys.exit(main())
  File "/home/alpine/.local/lib/python3.9/site-packages/win2xcur/main/win2xcur.py", line 58, in main
    pool.map(process, args.files)
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/alpine/.local/lib/python3.9/site-packages/win2xcur/main/win2xcur.py", line 50, in process
    shadow.apply_to_frames(cursor.frames, color=args.shadow_color, radius=args.shadow_radius,
  File "/home/alpine/.local/lib/python3.9/site-packages/win2xcur/shadow.py", line 39, in apply_to_frames
    cursor.image = apply_to_image(cursor.image, color=color, radius=radius,
  File "/home/alpine/.local/lib/python3.9/site-packages/win2xcur/shadow.py", line 23, in apply_to_image
    shadow.composite(opacity, operator='copy_opacity')
  File "/home/alpine/.local/lib/python3.9/site-packages/wand/image.py", line 1098, in wrapped
    result = function(self, *args, **kwargs)
  File "/home/alpine/.local/lib/python3.9/site-packages/wand/image.py", line 3906, in composite
    op = COMPOSITE_OPERATORS.index(operator)
ValueError: tuple.index(x): x not in tuple
```

**Comment by quantum5** [comment]
Seems like this time your install is missing the `copy_opacity` operation which is needed to generate shadows.

There are some specific instructions for wand on alpine: https://docs.wand-py.org/en/0.6.7/guide/install.html#install-wand-on-alpine. Maybe try those?

**Comment by Saijin-Naib** [comment]
Thanks for all your help!

Now I just need to figure out how to generate a cursor theme file/manifest so GNOME will use it properly!
